analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - packages/**/example/**
    - "**/example/**"
include: package:flutter_lints/flutter.yaml
