name: wikinusa
description: "An Android app for Wikipedia, Wiktionary and Wikibooks in local languages in Indonesia"
publish_to: 'none'
version: 1.5.3+6

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  beautiful_soup_dart: ^0.3.0
  easy_localization: ^3.0.8
  flutter_riverpod: ^3.2.1
  flutter_widget_from_html: ^0.17.2
  google_fonts: ^8.0.2
  html: ^0.15.6
  http: ^1.6.0
  just_audio: ^0.10.4
  just_audio_windows: ^0.2.3
  drift: ^2.24.0
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  share_plus: ^13.1.0
  shimmer: ^3.0.0
  home_widget: ^0.7.0
  url_launcher: ^6.3.2
  wikimedia_core:
    path: packages/wikimedia_core
  wikimedia_oauth2:
    path: packages/wikimedia_oauth2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.18.0
  drift_dev: ^2.24.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/images/onboarding1.webp
    - assets/images/onboarding2.webp
    - assets/images/onboarding3.webp
    - assets/images/onboarding4.webp
    - assets/images/onboarding5.webp
    - assets/translations/
    - assets/translations/en.json
    - assets/translations/id.json
    - assets/translations/nia.json

msix_config:
  display_name: WikiNusa
  publisher_display_name: "Sirus Laia"
  identity_name: sslaia.wikinusa
  msix_version: 1.5.2.0
  logo_path: assets/images/onboarding1.webp
  capabilities: internetClient
